language: node_js
sudo: false
node_js:
  - "6"
  - "8.9.4"
  - "9"

before_script:
  - npm install -g grunt-cli
  - npm install

script:
  - grunt
  - npm test
  # - npm run-script coverage

after_success:
  # - cat ./lib-cov/lcov.info |coveralls

